  version: '3.3'

  services:
    redis:
      image: "redis:4-alpine"
      env_file:
        - .env
      ports:
        - 6379:6379
      restart: always
      command: --requirepass ${REDIS_PWD}
    postgres:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: ${DB_SQL_PWD}
        POSTGRES_USER: ${DB_SQL_USER}
        POSTGRES_DB: ${DB_SQL_NAME}