CREATE SCHEMA IF NOT EXISTS tastes;

CREATE TABLE IF NOT EXISTS "tastes"."tastes" (
  "user_id" INTEGER NOT NULL REFERENCES "users"."users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "track_id" INTEGER NOT NULL REFERENCES "tracks"."tracks" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "deleted" BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("user_id", "track_id")
);
